// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function DownloadFile(arg1:string,arg2:string):Promise<app.ExcuteResult>;

export function Excute(arg1:Array<string>):Promise<app.ExcuteResult>;

export function ExcuteSync(arg1:Array<string>):Promise<app.ExcuteResult>;

export function GetCurrentActivity(arg1:string):Promise<app.Actitity>;

export function GetDeviceList():Promise<Array<string>>;

export function GetDeviceProp(arg1:string):Promise<app.DevicePropList>;

export function GetImage():Promise<number>;

export function InstallPackage(arg1:string):Promise<app.ExcuteResult>;

export function ListPath(arg1:string,arg2:string):Promise<app.ListFileRes>;

export function UploadFile(arg1:string,arg2:string):Promise<app.ExcuteResult>;
