// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Excute(arg1) {
  return window['go']['app']['App']['Excute'](arg1);
}

export function ExcuteSync(arg1) {
  return window['go']['app']['App']['ExcuteSync'](arg1);
}

export function GetDeviceList() {
  return window['go']['app']['App']['GetDeviceList']();
}

export function GetDeviceProp() {
  return window['go']['app']['App']['GetDeviceProp']();
}

export function GetImage() {
  return window['go']['app']['App']['GetImage']();
}

export function ListPath(arg1) {
  return window['go']['app']['App']['ListPath'](arg1);
}
