// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Excute(arg1:string):Promise<app.ExcuteResult>;

export function ExcuteSync(arg1:string):Promise<app.ExcuteResult>;

export function GetCurrentActivity():Promise<app.Actitity>;

export function GetDeviceList():Promise<Array<string>>;

export function GetDeviceProp():Promise<app.DevicePropList>;

export function GetImage():Promise<number>;

export function ListPath(arg1:string):Promise<app.ListFileRes>;
