// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1, arg2) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2);
}

export function Excute(arg1) {
  return window['go']['app']['App']['Excute'](arg1);
}

export function ExcuteSync(arg1) {
  return window['go']['app']['App']['ExcuteSync'](arg1);
}

export function ExcuteWithEnv(arg1) {
  return window['go']['app']['App']['ExcuteWithEnv'](arg1);
}

export function GetCurrentActivity(arg1) {
  return window['go']['app']['App']['GetCurrentActivity'](arg1);
}

export function GetDeviceList() {
  return window['go']['app']['App']['GetDeviceList']();
}

export function GetDeviceProp(arg1) {
  return window['go']['app']['App']['GetDeviceProp'](arg1);
}

export function GetImage() {
  return window['go']['app']['App']['GetImage']();
}

export function InstallPackage(arg1) {
  return window['go']['app']['App']['InstallPackage'](arg1);
}

export function ListPath(arg1, arg2) {
  return window['go']['app']['App']['ListPath'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['app']['App']['UploadFile'](arg1, arg2);
}
